# Gra
# Gracz
PLAYER_SPEED = 5

# Pocisk
BULLET_SPEED = 10

# Cele
TARGET_SPEED_MIN = 2
TARGET_SPEED_MAX = 3
SPAWN_RATE = 60
SPAWN_CHANCE_OPPONENT = 0.5
SPAWN_CHANCE_ALLY = 1 - SPAWN_CHANCE_OPPONENT
SHOOT_REWARD_OPPONENT = 30
SHOOT_REWARD_ALLY = -10
COLLISION_REWARD_OPPONENT = -5
COLLISION_REWARD_ALLY = 30
NO_COLLISION_REWARD_ALLY = -10
NO_COLLISION_REWARD_OPPONENT = -5

# Shooting cooldown
SHOOT_COOLDOWN_SECONDS = 20

# kolory
BLACK = (30, 30, 30)
WHITE = (255, 255, 255)
ORANGE = (236, 154, 109)

WIDTH = 400
HEIGHT = 300

# Inne
FPS = 90
SCALE_FACTOR = 5
